#!/usr/bin/env python3

# Turku backups - client agent
# Copyright (C) 2015-2020 Canonical Ltd., Ryan Finnie and other contributors
#
# SPDX-License-Identifer: GPL-3.0-or-later

import sys
from turku_agent import ping
sys.exit(ping.main())
