#!/usr/bin/env python3

# SPDX-PackageSummary: Turku backups - client agent
# SPDX-FileCopyrightText: Copyright (C) 2015-2020 Canonical Ltd.
# SPDX-FileCopyrightText: Copyright (C) 2015-2021 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: GPL-3.0-or-later

import sys
from turku_agent import ping
sys.exit(ping.main())
